# Generated by Django 2.1.7 on 2019-03-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, verbose_name='键')),
                ('value', models.CharField(max_length=255, verbose_name='值')),
            ],
            options={
                'verbose_name': '后台表',
                'verbose_name_plural': '后台表',
                'db_table': 'tb_backadmin',
            },
        ),
    ]
