# Generated by Django 2.1.7 on 2019-03-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='角色名')),
                ('desc', models.CharField(max_length=20, verbose_name='角色描述')),
                ('permissions', models.ManyToManyField(blank=True, to='user.Menu', verbose_name='URL授权')),
            ],
            options={
                'db_table': 'tb_role',
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='permissions',
        ),
    ]
