# Generated by Django 2.1.7 on 2019-03-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default='2000-1-1'),
        ),
    ]
