# Generated by Django 2.1.7 on 2019-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190322_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别'),
        ),
    ]
